export default {
  container: {
    flex: 1,
  },
  backgroundImage: {
    flex: 1,
    resizeMode: "cover",
  },

  img: {
    width: 73,
    height: 110,
    resizeMode: "contain",
  },
  centercontainer: {
    justifyContent: "center",
    alignItems: "center",
  },
  text: {
    fontSize: 18,
    color: "#FFFFFF",
    fontWeight: "bold",
    lineHeight: 17,
  },
  mainText: {
    fontSize: 30,
    textAlign: "center",
    fontWeight: "bold",
    color: "#6C3483",
    marginTop: 110,
    lineHeight: 40,
    marginBottom: 60,
  },
  clickText: {
    fontSize: 14,
    lineHeight: 30,
    textAlign: "center",
    fontWeight: "bold",
    color: "#6C3483",
    marginTop: 15,
    marginBottom: 80,
  },
  click1Text: {
    fontSize: 16,
    lineHeight: 30,
    textAlign: "center",
    fontWeight: "bold",
    color: "#6C3483",
    marginTop: 10,
    marginBottom: 80,
  },
  finishText: {
    fontSize: 26,
    textAlign: "center",
    fontWeight: "bold",
    color: "#6C3483",
    marginTop: 130,
    marginBottom: 90,
  },
  questionText: {
    fontSize: 22,
    lineHeight: 28,
    textAlign: "center",
    fontWeight: "bold",
    color: "#6C3483",
    marginLeft: 10,
    marginRight: 10,
  },

  gotext: {
    fontSize: 20,
    color: "white",
    fontWeight: "bold",

    textAlign: "center",
    alignItems: "center",
    justifyContent: "center",
  },
  rowcontainer: {
    flexDirection: "row",
  },
  col1: {
    flex: 1,
    borderRightWidth: 2,
    borderColor: "#FFFFFF",
    height: 120,
    justifyContent: "center",
    alignItems: "center",
  },
  col2: {
    flex: 1.7,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 15,
  },

  topIcon: {
    borderWidth: 2,
    borderColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    width: 300,
    height: 120,
    borderRadius: 10,
    marginTop: 60,
  },
  questionIcon: {
    borderWidth: 2,
    borderColor: "#6C3483",
    alignItems: "center",
    justifyContent: "center",
    width: 340,
    height: 140,
    textAlign: "center",
    marginTop: 30,
    borderRadius: 10,
  },
  minuteurImage: {
    marginTop: 30,
    width: 240,
    height: 240,
    resizeMode: "contain",
  },

  gotext: {
    fontSize: 20,
    color: "white",
    fontWeight: "bold",

    textAlign: "center",
    alignItems: "center",
    justifyContent: "center",
  },

  goIcon: {
    borderWidth: 1,
    borderColor: "#6C3483",
    alignItems: "center",
    justifyContent: "center",
    width: 80,
    height: 50,
    backgroundColor: "#6C3483",
    borderRadius: 10,
    marginTop: 40,
    marginBottom: 50,
  },
  beginText: {
    fontSize: 20,
    color: "white",
    fontWeight: "bold",

    textAlign: "center",
    alignItems: "center",
    justifyContent: "center",
  },

  beginIcon: {
    borderWidth: 1,
    borderColor: "#6C3483",
    alignItems: "center",
    justifyContent: "center",
    width: 180,
    height: 60,
    backgroundColor: "#6C3483",
    borderRadius: 10,
    marginTop: 80,
  },
};
